---
- name: Deploy application
  hosts: app
  tasks:
  - name: Update repository
    become: true
    apt_repository:
      repo: 'ppa:git-core/ppa'
      state: present
  - name: Install git
    become: true
    apt:
      name: git
      state: present
      update_cache: yes
  - name: Fetch the latest version of application code
    git:
      repo: 'https://github.com/express42/reddit.git'
      dest: /home/ubuntu/reddit
      version: monolith # <-- Указываем нужную ветку

  - name: Bundle install
    bundler:
      state: present
      chdir: /home/ubuntu/reddit # <-- В какой директории выполнить команду bundle
    notify: restart puma

  handlers:
  - name: restart puma
    become: true
    systemd: name=puma state=restarted


